---
argument_specs:
  main:
    short_description: Manage VCF Automation VPCs
    options:
      vcf_resource_state:
        type: str
        choices: [present, absent]
        default: present
      vcf_vpcs:
        type: list
        elements: dict
        required: true
        options:
          name: {type: str, required: true}
          labels: {type: dict}
          annotations: {type: dict}
          metadata: {type: dict}
          spec_overrides: {type: dict}
          project: {type: str}
          region_name: {type: str}
          vpc_class_name: {type: str}
